// components/About.tsx
"use client";

import { usePrefs } from "./Providers";
import { t } from "@/lib/i18n";
import type { AboutContent } from "@/lib/defaults";

export default function About({ content }: { content: AboutContent }) {
  const { lang } = usePrefs();
  return (
    <section className="section" id="about">
      <div className="container">
        <header className="section__head">
          <span className="section__num">{t(content.section_num, lang)}</span>
          <h2
            className="section__title"
            dangerouslySetInnerHTML={{ __html: t(content.title_html, lang) }}
          />
        </header>

        <div className="about__grid">
          <div className="about__prose">
            {content.paragraphs_html.map((p, i) => (
              <p key={i} dangerouslySetInnerHTML={{ __html: t(p, lang) }} />
            ))}

            <blockquote className="quote">
              <span className="quote__mark" aria-hidden>
                {"/*"}
              </span>
              <p dangerouslySetInnerHTML={{ __html: t(content.quote_html, lang) }} />
              <span className="quote__mark quote__mark--end" aria-hidden>
                {"*/"}
              </span>
            </blockquote>

            <p className="about__sig">
              — KN, <span className="dim">{t(content.sig_prefix, lang)}</span>
              <time dateTime={content.sig_year}>{content.sig_year}</time>
            </p>
          </div>

          <aside className="about__card">
            <header className="card__head">
              <span className="card__label">{content.card_label}</span>
              <span className="card__dot" aria-hidden />
            </header>
            <dl className="about__meta">
              {content.card_meta.map((row, i) => (
                <div key={i}>
                  <dt>{t(row.key, lang)}</dt>
                  <dd>{t(row.value, lang)}</dd>
                </div>
              ))}
            </dl>
          </aside>
        </div>
      </div>
    </section>
  );
}

// app/components/About.vue
<script setup lang="ts">
import type { AboutContent } from '~/lib/defaults'

defineProps<{ content: AboutContent }>()

const { t } = useI18n()
</script>

<template>
  <section class="section" id="about">
    <div class="container">
      <header class="section__head">
        <span class="section__num">{{ t(content.section_num) }}</span>
        <h2 class="section__title" v-html="t(content.title_html)" />
      </header>

      <div class="about__grid">
        <div class="about__prose">
          <p v-for="(p, i) in content.paragraphs_html" :key="i" v-html="t(p)" />

          <blockquote class="quote">
            <span class="quote__mark" aria-hidden>/*</span>
            <p v-html="t(content.quote_html)" />
            <span class="quote__mark quote__mark--end" aria-hidden>*/</span>
          </blockquote>

          <p class="about__sig">
            — KN, <span class="dim">{{ t(content.sig_prefix) }}</span>
            <time :datetime="content.sig_year">{{ content.sig_year }}</time>
          </p>
        </div>

        <aside class="about__card">
          <header class="card__head">
            <span class="card__label">{{ content.card_label }}</span>
            <span class="card__dot" aria-hidden />
          </header>
          <dl class="about__meta">
            <div v-for="(row, i) in content.card_meta" :key="i">
              <dt>{{ t(row.key) }}</dt>
              <dd>{{ t(row.value) }}</dd>
            </div>
          </dl>
        </aside>
      </div>
    </div>
  </section>
</template>
