// components/Marquee.tsx
import { Fragment } from "react";
import type { MarqueeContent } from "@/lib/defaults";

export default function Marquee({ content }: { content: MarqueeContent }) {
  // Duplicate the item list so a -50% translate produces a seamless loop.
  const items = [...content.items, ...content.items];

  // Mobile pill — show one curated item (prefer the dotted "status" entry,
  // otherwise just the first). Keeps the bar quiet on small screens.
  const pillItem =
    content.items.find((it) => it.dot) ?? content.items[0] ?? { text: "", dot: false };

  return (
    <div className="marquee" aria-hidden>
      <div className="marquee__track">
        {items.map((item, i) => (
          <Fragment key={i}>
            <span className="marquee__item">
              {item.dot ? <span className="marquee__dot" /> : null}
              {item.text}
            </span>
            <span className="marquee__sep">✦</span>
          </Fragment>
        ))}
      </div>
      <div className="marquee__pill">
        <span className="marquee__item">
          {pillItem.dot ? <span className="marquee__dot" /> : null}
          {pillItem.text}
        </span>
      </div>
    </div>
  );
}

// app/components/Marquee.vue
<script setup lang="ts">
import type { MarqueeContent } from '~/lib/defaults'

const props = defineProps<{ content: MarqueeContent }>()

// Duplicate the item list so a -50% translate produces a seamless loop.
const items = computed(() => [...props.content.items, ...props.content.items])

// Mobile pill — prefer the dotted "status" entry, otherwise the first item.
const pillItem = computed(
  () => props.content.items.find((it) => it.dot) ?? props.content.items[0] ?? { text: '', dot: false },
)
</script>

<template>
  <div class="marquee" aria-hidden>
    <div class="marquee__track">
      <template v-for="(item, i) in items" :key="i">
        <span class="marquee__item">
          <span v-if="item.dot" class="marquee__dot" />
          {{ item.text }}
        </span>
        <span class="marquee__sep">✦</span>
      </template>
    </div>
    <div class="marquee__pill">
      <span class="marquee__item">
        <span v-if="pillItem.dot" class="marquee__dot" />
        {{ pillItem.text }}
      </span>
    </div>
  </div>
</template>
